// Static browsable reflection of Roadmap and its milestone attribute.
export default [
  [
    { kind: 'identity', value: 'cdd.roadmap' },
    { kind: 'concept', value: 'cdd.concept' },
    { kind: 'slug', value: 'roadmap' },
    { kind: 'name', value: 'Roadmap' },
    {
      kind: 'definition',
      value:
        'A step-wise plan to implement a [project](cdd.project). It is a directed acyclic graph of steps: a task to do, a goal to achieve, or a problem to solve.',
    },
    { kind: 'attributes', value: ['cdd.roadmap:steps', 'cdd.roadmap:milestones', 'cdd.roadmap:diagram'] },
    { kind: 'examples', value: ['cdd.roadmap:examples:publicRelease'] },
  ],
  [
    { kind: 'identity', value: 'cdd.roadmap:steps' },
    { kind: 'concept', value: 'cdd.attribute' },
    { kind: 'slug', value: 'steps' },
    { kind: 'name', value: 'steps' },
    { kind: 'type', value: 'cdd.roadmapStep' },
    { kind: 'cardinality', value: '1+' },
  ],
  [
    { kind: 'identity', value: 'cdd.roadmap:milestones' },
    { kind: 'concept', value: 'cdd.attribute' },
    { kind: 'slug', value: 'milestones' },
    { kind: 'name', value: 'milestones' },
    { kind: 'type', value: 'cdd.milestone' },
    { kind: 'cardinality', value: '0+' },
    { kind: 'description', value: 'Ordered, non-overlapping phases whose step memberships are exclusive.' },
  ],
  [
    { kind: 'identity', value: 'cdd.roadmap:diagram' },
    { kind: 'concept', value: 'cdd.attribute' },
    { kind: 'slug', value: 'diagram' },
    { kind: 'name', value: 'diagram' },
    { kind: 'type', value: 'cdd.scheme' },
    { kind: 'cardinality', value: '1' },
  ],
  [
    { kind: 'identity', value: 'cdd.roadmapStep' },
    { kind: 'concept', value: 'cdd.concept' },
    { kind: 'slug', value: 'roadmapStep' },
    { kind: 'name', value: 'Roadmap step' },
    { kind: 'definition', value: 'A task to do, a goal to achieve, or a problem to solve in a roadmap.' },
    { kind: 'attributes', value: ['cdd.roadmapStep:kind', 'cdd.roadmapStep:dependsOn'] },
  ],
  [
    { kind: 'identity', value: 'cdd.roadmapStep:kind' },
    { kind: 'concept', value: 'cdd.attribute' },
    { kind: 'slug', value: 'kind' },
    { kind: 'name', value: 'kind' },
    { kind: 'type', value: 'cdd.string' },
    { kind: 'cardinality', value: '1' },
    { kind: 'description', value: 'One of: task, goal, or problem.' },
  ],
  [
    { kind: 'identity', value: 'cdd.roadmapStep:dependsOn' },
    { kind: 'concept', value: 'cdd.attribute' },
    { kind: 'slug', value: 'dependsOn' },
    { kind: 'name', value: 'depends on' },
    { kind: 'type', value: 'cdd.roadmapStep' },
    { kind: 'cardinality', value: '0+' },
  ],
  [
    { kind: 'identity', value: 'cdd.milestone' },
    { kind: 'concept', value: 'cdd.concept' },
    { kind: 'slug', value: 'milestone' },
    { kind: 'name', value: 'Milestone' },
    { kind: 'definition', value: 'An ordered phase in a [roadmap](cdd.roadmap). Its steps belong to no other milestone in that roadmap.' },
    { kind: 'attributes', value: ['cdd.milestone:steps'] },
  ],
  [
    { kind: 'identity', value: 'cdd.milestone:steps' },
    { kind: 'concept', value: 'cdd.attribute' },
    { kind: 'slug', value: 'steps' },
    { kind: 'name', value: 'steps' },
    { kind: 'type', value: 'cdd.roadmapStep' },
    { kind: 'cardinality', value: '1+' },
    { kind: 'description', value: 'The roadmap steps exclusively owned by this milestone.' },
  ],
  [
    { kind: 'identity', value: 'cdd.roadmap:examples:publicRelease' },
    { kind: 'concept', value: 'cdd.example' },
    { kind: 'name', value: 'CDD public-release roadmap' },
    { kind: 'instance', value: 'cdd.roadmap:examples:cddPublicRelease:roadmap' },
    {
      kind: 'description',
      value:
        'A navigable roadmap instance for the CDD project. Its diagram renders the dependency DAG and labels its milestone subtrees.',
    },
  ],
  [
    { kind: 'identity', value: 'cdd.roadmap:examples:cddPublicRelease:roadmap' },
    { kind: 'concept', value: 'cdd.roadmap' },
    { kind: 'name', value: 'CDD public release' },
    { kind: 'description', value: 'A roadmap for making CDD usable from a fresh checkout and publishing its first release.' },
    { kind: 'steps', value: [
      'cdd.roadmap:examples:cddPublicRelease:problem',
      'cdd.roadmap:examples:cddPublicRelease:goal',
      'cdd.roadmap:examples:cddPublicRelease:writeInstaller',
      'cdd.roadmap:examples:cddPublicRelease:packageCli',
      'cdd.roadmap:examples:cddPublicRelease:releaseAutomation',
      'cdd.roadmap:examples:cddPublicRelease:integrationTests',
      'cdd.roadmap:examples:cddPublicRelease:documentInstallation',
      'cdd.roadmap:examples:cddPublicRelease:freshCheckoutTest',
      'cdd.roadmap:examples:cddPublicRelease:publishDocs',
      'cdd.roadmap:examples:cddPublicRelease:publishRelease',
      'cdd.roadmap:examples:cddPublicRelease:announceRelease',
      'cdd.roadmap:examples:cddPublicRelease:collectFeedback',
    ] },
    { kind: 'milestones', value: [
      'cdd.roadmap:examples:cddPublicRelease:foundation',
      'cdd.roadmap:examples:cddPublicRelease:implementation',
      'cdd.roadmap:examples:cddPublicRelease:validation',
      'cdd.roadmap:examples:cddPublicRelease:publicRelease',
    ] },
    { kind: 'diagram', value: 'cdd.roadmap:examples:cddPublicRelease:diagram' },
  ],
  [
    { kind: 'identity', value: 'cdd.roadmap:examples:cddPublicRelease:problem' },
    { kind: 'concept', value: 'cdd.roadmapStep' },
    { kind: 'name', value: 'Fresh checkout is unusable' },
    { kind: 'description', value: 'Problem: a developer cannot yet use CDD from a fresh checkout.' },
    { kind: 'kind', value: 'problem' },
  ],
  [
    { kind: 'identity', value: 'cdd.roadmap:examples:cddPublicRelease:goal' },
    { kind: 'concept', value: 'cdd.roadmapStep' },
    { kind: 'name', value: 'CDD is usable after installation' },
    { kind: 'description', value: 'Goal: a developer can install and use CDD.' },
    { kind: 'kind', value: 'goal' },
    { kind: 'dependsOn', value: ['cdd.roadmap:examples:cddPublicRelease:problem'] },
  ],
  [
    { kind: 'identity', value: 'cdd.roadmap:examples:cddPublicRelease:writeInstaller' },
    { kind: 'concept', value: 'cdd.roadmapStep' },
    { kind: 'name', value: 'Write the installer' },
    { kind: 'description', value: 'Task: write the installer for CDD.' },
    { kind: 'kind', value: 'task' },
    { kind: 'dependsOn', value: ['cdd.roadmap:examples:cddPublicRelease:goal'] },
  ],
  [
    { kind: 'identity', value: 'cdd.roadmap:examples:cddPublicRelease:documentInstallation' },
    { kind: 'concept', value: 'cdd.roadmapStep' },
    { kind: 'name', value: 'Document installation' },
    { kind: 'description', value: 'Task: document how to install CDD.' },
    { kind: 'kind', value: 'task' },
    { kind: 'dependsOn', value: [
      'cdd.roadmap:examples:cddPublicRelease:writeInstaller',
      'cdd.roadmap:examples:cddPublicRelease:packageCli',
    ] },
  ],
  ...[
    ['packageCli', 'Package the CDD CLI', 'Package the CLI for installation.', ['goal']],
    ['releaseAutomation', 'Automate the release', 'Configure reproducible release automation.', ['goal']],
    ['integrationTests', 'Run integration tests', 'Verify the installer and packaged CLI together.', ['writeInstaller', 'packageCli']],
    ['freshCheckoutTest', 'Test a fresh checkout', 'Verify the documented installation from a fresh checkout.', ['integrationTests', 'documentInstallation']],
    ['publishDocs', 'Publish installation docs', 'Publish the validated installation documentation.', ['documentInstallation', 'integrationTests']],
  ].map(([slug, name, description, dependencies]) => [
    { kind: 'identity', value: `cdd.roadmap:examples:cddPublicRelease:${slug}` },
    { kind: 'concept', value: 'cdd.roadmapStep' },
    { kind: 'name', value: name },
    { kind: 'description', value: `Task: ${description}` },
    { kind: 'kind', value: 'task' },
    { kind: 'dependsOn', value: (dependencies as string[]).map((dependency) => `cdd.roadmap:examples:cddPublicRelease:${dependency}`) },
  ]),
  [
    { kind: 'identity', value: 'cdd.roadmap:examples:cddPublicRelease:publishRelease' },
    { kind: 'concept', value: 'cdd.roadmapStep' },
    { kind: 'name', value: 'Publish the first release' },
    { kind: 'description', value: 'Task: publish the first CDD release.' },
    { kind: 'kind', value: 'task' },
    { kind: 'dependsOn', value: [
      'cdd.roadmap:examples:cddPublicRelease:freshCheckoutTest',
      'cdd.roadmap:examples:cddPublicRelease:publishDocs',
      'cdd.roadmap:examples:cddPublicRelease:releaseAutomation',
    ] },
  ],
  ...[
    ['announceRelease', 'Announce the release', 'Announce the first public CDD release.'],
    ['collectFeedback', 'Collect early feedback', 'Invite and collect feedback from early users.'],
  ].map(([slug, name, description]) => [
    { kind: 'identity', value: `cdd.roadmap:examples:cddPublicRelease:${slug}` },
    { kind: 'concept', value: 'cdd.roadmapStep' },
    { kind: 'name', value: name },
    { kind: 'description', value: `Task: ${description}` },
    { kind: 'kind', value: 'task' },
    { kind: 'dependsOn', value: ['cdd.roadmap:examples:cddPublicRelease:publishRelease'] },
  ]),
  [
    { kind: 'identity', value: 'cdd.roadmap:examples:cddPublicRelease:foundation' },
    { kind: 'concept', value: 'cdd.milestone' },
    { kind: 'name', value: 'Foundation' },
    { kind: 'steps', value: [
      'cdd.roadmap:examples:cddPublicRelease:problem',
      'cdd.roadmap:examples:cddPublicRelease:goal',
    ] },
  ],
  [
    { kind: 'identity', value: 'cdd.roadmap:examples:cddPublicRelease:implementation' },
    { kind: 'concept', value: 'cdd.milestone' },
    { kind: 'name', value: 'Implementation' },
    { kind: 'steps', value: [
      'cdd.roadmap:examples:cddPublicRelease:writeInstaller',
      'cdd.roadmap:examples:cddPublicRelease:packageCli',
      'cdd.roadmap:examples:cddPublicRelease:releaseAutomation',
    ] },
  ],
  [
    { kind: 'identity', value: 'cdd.roadmap:examples:cddPublicRelease:validation' },
    { kind: 'concept', value: 'cdd.milestone' },
    { kind: 'name', value: 'Validation' },
    { kind: 'steps', value: [
      'cdd.roadmap:examples:cddPublicRelease:integrationTests',
      'cdd.roadmap:examples:cddPublicRelease:documentInstallation',
      'cdd.roadmap:examples:cddPublicRelease:freshCheckoutTest',
      'cdd.roadmap:examples:cddPublicRelease:publishDocs',
    ] },
  ],
  [
    { kind: 'identity', value: 'cdd.roadmap:examples:cddPublicRelease:publicRelease' },
    { kind: 'concept', value: 'cdd.milestone' },
    { kind: 'name', value: 'Public release' },
    { kind: 'steps', value: [
      'cdd.roadmap:examples:cddPublicRelease:publishRelease',
      'cdd.roadmap:examples:cddPublicRelease:announceRelease',
      'cdd.roadmap:examples:cddPublicRelease:collectFeedback',
    ] },
  ],
  [
    { kind: 'identity', value: 'cdd.roadmap:examples:cddPublicRelease:diagram' },
    { kind: 'concept', value: 'cdd.scheme' },
    { kind: 'direction', value: 'bottomToTop' },
    { kind: 'boxes', value: [
      'cdd.roadmap:examples:cddPublicRelease:diagram:problem',
      'cdd.roadmap:examples:cddPublicRelease:diagram:goal',
      'cdd.roadmap:examples:cddPublicRelease:diagram:installer',
      'cdd.roadmap:examples:cddPublicRelease:diagram:cli',
      'cdd.roadmap:examples:cddPublicRelease:diagram:automation',
      'cdd.roadmap:examples:cddPublicRelease:diagram:tests',
      'cdd.roadmap:examples:cddPublicRelease:diagram:documentation',
      'cdd.roadmap:examples:cddPublicRelease:diagram:freshCheckout',
      'cdd.roadmap:examples:cddPublicRelease:diagram:publishDocs',
      'cdd.roadmap:examples:cddPublicRelease:diagram:release',
      'cdd.roadmap:examples:cddPublicRelease:diagram:announce',
      'cdd.roadmap:examples:cddPublicRelease:diagram:feedback',
    ] },
    { kind: 'edges', value: [
      'cdd.roadmap:examples:cddPublicRelease:diagram:problemToGoal',
      'cdd.roadmap:examples:cddPublicRelease:diagram:goalToInstaller',
      'cdd.roadmap:examples:cddPublicRelease:diagram:goalToCli',
      'cdd.roadmap:examples:cddPublicRelease:diagram:goalToAutomation',
      'cdd.roadmap:examples:cddPublicRelease:diagram:installerToTests',
      'cdd.roadmap:examples:cddPublicRelease:diagram:cliToTests',
      'cdd.roadmap:examples:cddPublicRelease:diagram:installerToDocumentation',
      'cdd.roadmap:examples:cddPublicRelease:diagram:cliToDocumentation',
      'cdd.roadmap:examples:cddPublicRelease:diagram:testsToFreshCheckout',
      'cdd.roadmap:examples:cddPublicRelease:diagram:documentationToFreshCheckout',
      'cdd.roadmap:examples:cddPublicRelease:diagram:testsToPublishDocs',
      'cdd.roadmap:examples:cddPublicRelease:diagram:documentationToPublishDocs',
      'cdd.roadmap:examples:cddPublicRelease:diagram:freshCheckoutToRelease',
      'cdd.roadmap:examples:cddPublicRelease:diagram:publishDocsToRelease',
      'cdd.roadmap:examples:cddPublicRelease:diagram:automationToRelease',
      'cdd.roadmap:examples:cddPublicRelease:diagram:releaseToAnnounce',
      'cdd.roadmap:examples:cddPublicRelease:diagram:releaseToFeedback',
    ] },
  ],
  ...[
    ['problem', 'Problem\nFresh checkout is unusable', 'cdd.roadmap:examples:cddPublicRelease:problem', '#b91c1c'],
    ['goal', 'Goal\nCDD is usable after installation', 'cdd.roadmap:examples:cddPublicRelease:goal', '#15803d'],
    ['installer', 'Task\nWrite the installer', 'cdd.roadmap:examples:cddPublicRelease:writeInstaller', '#1d4ed8'],
    ['cli', 'Task\nPackage the CDD CLI', 'cdd.roadmap:examples:cddPublicRelease:packageCli', '#1d4ed8'],
    ['automation', 'Task\nAutomate the release', 'cdd.roadmap:examples:cddPublicRelease:releaseAutomation', '#1d4ed8'],
    ['tests', 'Task\nRun integration tests', 'cdd.roadmap:examples:cddPublicRelease:integrationTests', '#1d4ed8'],
    ['documentation', 'Task\nDocument installation', 'cdd.roadmap:examples:cddPublicRelease:documentInstallation', '#1d4ed8'],
    ['freshCheckout', 'Task\nTest a fresh checkout', 'cdd.roadmap:examples:cddPublicRelease:freshCheckoutTest', '#1d4ed8'],
    ['publishDocs', 'Task\nPublish installation docs', 'cdd.roadmap:examples:cddPublicRelease:publishDocs', '#1d4ed8'],
    ['release', 'Task\nPublish the first release', 'cdd.roadmap:examples:cddPublicRelease:publishRelease', '#1d4ed8'],
    ['announce', 'Task\nAnnounce the release', 'cdd.roadmap:examples:cddPublicRelease:announceRelease', '#1d4ed8'],
    ['feedback', 'Task\nCollect early feedback', 'cdd.roadmap:examples:cddPublicRelease:collectFeedback', '#1d4ed8'],
  ].map(([slug, content, denotatum, borderColor]) => [
    { kind: 'identity', value: `cdd.roadmap:examples:cddPublicRelease:diagram:${slug}` },
    { kind: 'concept', value: 'cdd.schemeBox' },
    { kind: 'content', value: content },
    { kind: 'denotatum', value: denotatum },
    { kind: 'borderColor', value: borderColor },
    { kind: 'padding', value: '14' },
  ]),
  ...[
    ['problemToGoal', 'problem', 'goal'],
    ['goalToInstaller', 'goal', 'installer'],
    ['goalToCli', 'goal', 'cli'],
    ['goalToAutomation', 'goal', 'automation'],
    ['installerToTests', 'installer', 'tests'],
    ['cliToTests', 'cli', 'tests'],
    ['installerToDocumentation', 'installer', 'documentation'],
    ['cliToDocumentation', 'cli', 'documentation'],
    ['testsToFreshCheckout', 'tests', 'freshCheckout'],
    ['documentationToFreshCheckout', 'documentation', 'freshCheckout'],
    ['testsToPublishDocs', 'tests', 'publishDocs'],
    ['documentationToPublishDocs', 'documentation', 'publishDocs'],
    ['freshCheckoutToRelease', 'freshCheckout', 'release'],
    ['publishDocsToRelease', 'publishDocs', 'release'],
    ['automationToRelease', 'automation', 'release'],
    ['releaseToAnnounce', 'release', 'announce'],
    ['releaseToFeedback', 'release', 'feedback'],
  ].map(([slug, source, target]) => [
    { kind: 'identity', value: `cdd.roadmap:examples:cddPublicRelease:diagram:${slug}` },
    { kind: 'concept', value: 'cdd.schemeEdge' },
    { kind: 'source', value: `cdd.roadmap:examples:cddPublicRelease:diagram:${source}` },
    { kind: 'target', value: `cdd.roadmap:examples:cddPublicRelease:diagram:${target}` },
    { kind: 'content', value: 'depends on' },
    { kind: 'color', value: '#7c3aed' },
    { kind: 'routing', value: 'orthogonal' },
    { kind: 'startHead', value: 'none' },
    { kind: 'endHead', value: 'arrow' },
  ]),
]
