import type { PropertyKindName } from '@/concepts/properties/Property'

// How a property's value is edited:
//  - literal:       a single string (v-text-field)
//  - literal-list:  a list of free strings (v-combobox with chips)
//  - concept-list:  a list of concept identities picked from the ontology
//  - readonly:      not editable (identity)
export type PropertyValueKind = 'literal' | 'literal-list' | 'concept-list' | 'readonly'

export const propertyValueKind: Record<PropertyKindName, PropertyValueKind> = {
  identity: 'readonly',
  slug: 'literal',
  name: 'literal',
  definition: 'literal',
  description: 'literal',
  details: 'literal',
  examples: 'literal-list',
  inspirations: 'literal-list',
  concept: 'concept-list',
  concepts: 'concept-list',
  attributes: 'concept-list',
  transactions: 'concept-list',
  effect: 'literal',
  params: 'literal-list',
  layers: 'literal-list',
  concerns: 'literal-list',
  required: 'literal',
  type: 'concept-list',
  cardinality: 'literal',
  instance: 'concept-list',
  parentConcept: 'concept-list',
  canonicalName: 'readonly',
  computed: 'literal',
  function: 'literal',
  scheme: 'concept-list',
  exampleDiagram: 'concept-list',
  ontologyDiagram: 'concept-list',
  boxes: 'concept-list',
  edges: 'concept-list',
  texts: 'concept-list',
  content: 'literal',
  denotatum: 'concept-list',
  color: 'literal',
  backgroundColor: 'literal',
  borderColor: 'literal',
  padding: 'literal',
  source: 'literal',
  target: 'literal',
  lineStyle: 'literal',
  routing: 'literal',
  boldness: 'literal',
  startHead: 'literal',
  endHead: 'literal',
  align: 'literal',
  prototypeImage: 'concept-list',
  url: 'literal',
  blob: 'literal',
}

export const ALL_PROPERTY_KINDS: PropertyKindName[] = [
  'identity',
  'slug',
  'name',
  'definition',
  'description',
  'details',
  'examples',
  'inspirations',
  'concept',
  'concepts',
  'attributes',
  'transactions',
  'effect',
  'params',
  'layers',
  'concerns',
  'required',
  'type',
  'cardinality',
  'instance',
  'parentConcept',
  'canonicalName',
  'computed',
  'function',
  'scheme',
  'exampleDiagram',
  'ontologyDiagram',
  'boxes',
  'edges',
  'texts',
  'content',
  'denotatum',
  'color',
  'backgroundColor',
  'borderColor',
  'padding',
  'source',
  'target',
  'lineStyle',
  'routing',
  'boldness',
  'startHead',
  'endHead',
  'align',
  'prototypeImage',
  'url',
  'blob',
]
